[package]
name = "ripb"
version = "0.1.0"
authors = ["Thibaut Lorrain <fredszaq@gmail.com>"]

[dependencies]
crossbeam-channel = "0.2"
log = "0.4"
num_cpus = "1.8"

[dev-dependencies]
bencher = "0.1"


[[bench]]
name = "bench"
harness = false
